module Tessarium.Table.Data

/// GENERATED by `python3 grid_design.py --emit-fstar` from design/bands.json.
/// DO NOT EDIT.
///
/// `cumcols_list` is abstract on purpose. The implementation holds 4097
/// literals, and a module that lets those into its SMT encoding cannot
/// discharge even a trivial index bound. Everything downstream works from the
/// two lemmas below instead.

module L = FStar.List.Tot

open Tessarium.Scan

let grid_version : string = "tessarium-grid-3"

let rows          : pos = 6553600
let bands         : pos = 4096
let rows_per_band : pos = 1600
let total_cells   : pos = 55692067744000

/// Widest band, at the equator. Bounds every intermediate in the encode path.
let max_col_count : pos = 13343409

/// Cumulative column counts: cum[b] is the total number of columns in every
/// band before b. Storing the running total rather than the two tables the
/// grid consumes is what makes band-offset contiguity true by definition:
/// offsets[b] is cum[b] * rows_per_band and col_counts[b] is cum[b+1] - cum[b].
/// The length lives in the type rather than in a lemma, so that indexing the
/// table is well-typed everywhere without first calling something.
val cumcols_list : l: list nat{Cons? l /\ L.length l == bands + 1}

/// Adjacent differences lie in (0, max_col_count]. Strict increase gives every
/// band a positive column count; the bound gives the per-band width limit.
val lemma_diffs : unit -> Lemma (diffs_ok cumcols_list max_col_count)

/// The table starts at zero, so band 0 begins at cell 0.
val lemma_base : unit -> Lemma (L.index cumcols_list 0 == 0)

/// The grand total, which is what makes the grid fit the address space.
val lemma_total : unit -> Lemma (L.index cumcols_list bands * rows_per_band == total_cells)
