module Tessarium.Grid

/// Banded grid: point <-> cell index.
/// NOT YET VERIFIED.

open FStar.Mul
open Tessarium.Spec

/// Generated by design/grid_design.py. The table is data, not code; its
/// properties below are what the rest of the development relies on.
val rows          : pos
val bands         : pos
val rows_per_band : pos
val total_cells   : pos

val col_counts : i:nat{i < bands} -> pos
val offsets    : i:nat{i < bands} -> nat

type cell = c:nat{c < total_cells}

(* -------------------------------------------- band table well-formedness *)

/// Discharged once against the generated table, then used everywhere.

val lemma_rows_divide : unit -> Lemma (rows == bands * rows_per_band)

val lemma_offsets_contiguous (b: nat{b < bands - 1})
  : Lemma (offsets (b + 1) == offsets b + col_counts b * rows_per_band)

val lemma_offsets_base : unit -> Lemma (offsets 0 == 0)

val lemma_total (_: unit)
  : Lemma (offsets (bands - 1) + col_counts (bands - 1) * rows_per_band == total_cells)

/// The grid must fit inside the address space, or encode could produce an
/// index the Feistel cannot represent.
val lemma_fits : unit -> Lemma (total_cells < addr_space)

/// Needed for lemma_midpoint_interior at every band.
val lemma_cells_wide (b: nat{b < bands})
  : Lemma (lon_span >= 2 * col_counts b /\ lat_span >= 2 * rows)

(* ---------------------------------------------------------------- the map *)

val point_to_cell : lat_ns -> lon_ns -> cell
val cell_to_point : cell -> lat_ns & lon_ns
val cell_bounds   : cell -> (int & int & int & int)

(* ----------------------------------------------------------- the theorems *)

/// THEOREM 1. Every cell's representative point re-encodes to that cell.
/// This is what makes decode(encode(p)) meaningful.
val theorem_roundtrip (c: cell)
  : Lemma (let lat, lon = cell_to_point c in point_to_cell lat lon == c)

/// THEOREM 2. The map is injective: two points sharing a cell index lie in
/// the same cell bounds. Includes behaviour at band seams, which is where a
/// banded grid can gap or overlap and where ordinary testing is weakest,
/// since the failure set has measure zero.
val theorem_injective (lat1: lat_ns) (lon1: lon_ns) (lat2: lat_ns) (lon2: lon_ns)
  : Lemma (requires point_to_cell lat1 lon1 == point_to_cell lat2 lon2)
          (ensures  (let a_lo, a_hi, o_lo, o_hi = cell_bounds (point_to_cell lat1 lon1) in
                     a_lo <= lat1 /\ lat1 < a_hi /\ o_lo <= lon1 /\ lon1 < o_hi /\
                     a_lo <= lat2 /\ lat2 < a_hi /\ o_lo <= lon2 /\ lon2 < o_hi))

/// THEOREM 3. Every point lands inside its own cell. Stated separately
/// because it is the property the reference implementation initially
/// violated, at exactly one nanodegree per cell edge.
val theorem_containment (lat: lat_ns) (lon: lon_ns)
  : Lemma (let a_lo, a_hi, o_lo, o_hi = cell_bounds (point_to_cell lat lon) in
           a_lo <= lat /\ lat < a_hi /\ o_lo <= lon /\ lon < o_hi)

/// No intermediate product exceeds 64 bits. The widest is
/// lon_span * max(col_counts) = 4.80e18, which fits signed int64 with 1.92x
/// headroom and uint64 with 3.84x. Tight enough to be worth proving rather
/// than assuming.
val theorem_no_overflow (b: nat{b < bands})
  : Lemma (lon_span * col_counts b < pow2 63 /\ lat_span * rows < pow2 63)
