/* The country and state catalogue behind the download picker.

   Data is committed (ui/src/regions.json, regenerated by
   tools/gen-regions.py from Natural Earth, public domain) so the build needs
   no network and the list cannot drift silently. Cities are points in the
   source data; their boxes are drawn by the generator, sized by prominence
   and latitude. Names are localised at
   runtime with Intl.DisplayNames from the ISO codes -- the one place the
   browser ships a full gazetteer -- with the dataset's English name as the
   fallback; subdivision names have no Intl support and are shown as named.

   Boxes, not polygons: a country download includes slivers of neighbours,
   and antimeridian countries (Russia, Fiji) get a near-world-wide box that
   the server's tile budget keeps affordable. Both noted on the roadmap. */

import { z } from "zod";
import type { Region } from "./core/basemap";
import { getLocale } from "./i18n";
import data from "./regions.json";

const Box = z.tuple([z.number(), z.number(), z.number(), z.number()]);
const Catalogue = z.object({
  countries: z.array(z.object({
    code: z.string().nullable(),
    name: z.string(),
    bbox: Box,
  })),
  subdivisions: z.record(
    z.string(),
    z.array(z.object({ name: z.string(), bbox: Box })),
  ),
  cities: z.record(
    z.string(),
    z.array(z.object({ name: z.string(), bbox: Box })),
  ),
});

/* Parsed once at module load: the file is committed, so a mistake here is a
   build-time accident, and it should fail the first render loudly rather
   than surface as an empty picker. */
const catalogue = Catalogue.parse(data);

export type Country = (typeof catalogue.countries)[number];
export type Subdivision = {
  name: string;
  bbox: [number, number, number, number];
};

export const countryName = (country: Country): string => {
  if (country.code) {
    try {
      const display = new Intl.DisplayNames([getLocale()], { type: "region" });
      return display.of(country.code) ?? country.name;
    } catch {
      /* An unknown code falls back to the dataset's name. */
    }
  }
  return country.name;
};

/* Sorted for the current locale on every call, because the locale can change
   under a live picker and "Germany" and "Allemagne" sort differently. */
export const countries = (): { country: Country; label: string; }[] => {
  const collator = new Intl.Collator(getLocale());
  return catalogue.countries
    .map((country) => ({ country, label: countryName(country) }))
    .sort((a, b) => collator.compare(a.label, b.label));
};

export const subdivisionsOf = (country: Country): Subdivision[] =>
  country.code ? catalogue.subdivisions[country.code] ?? [] : [];

/* Cities share the subdivision shape: a named box. */
export const citiesOf = (country: Country): Subdivision[] =>
  country.code ? catalogue.cities[country.code] ?? [] : [];

export const toRegion = (
  bbox: [number, number, number, number],
): Region => ({
  min_lon: bbox[0],
  min_lat: bbox[1],
  max_lon: bbox[2],
  max_lat: bbox[3],
  max_zoom: 15,
});
