/* The country and state catalogue behind the download picker.

   Data is committed (ui/src/regions.json, regenerated by
   tools/gen-regions.py from Natural Earth, public domain) so the build needs
   no network and the list cannot drift silently. Cities are points in the
   source data; their boxes are drawn by the generator, sized by prominence
   and latitude. Names are localised at
   runtime with Intl.DisplayNames from the ISO codes -- the one place the
   browser ships a full gazetteer -- with the dataset's English name as the
   fallback; subdivision names have no Intl support and are shown as named.

   Boxes, not polygons: a country download includes slivers of neighbours,
   and antimeridian countries (Russia, Fiji) get a near-world-wide box that
   the server's tile budget keeps affordable. Both noted on the roadmap. */

import { z } from "zod";
import type { Region } from "./core/basemap";
import { getLocale } from "./i18n";
import data from "./regions.json";

const Box = z.tuple([z.number(), z.number(), z.number(), z.number()]);
const Ring = z.array(z.tuple([z.number(), z.number()]));
/* Boxes, plural: a country astride the antimeridian (Russia) is two honest
   boxes rather than one world-wide one, and the download API happily takes
   several regions. Country polygons clip the download to the border. */
const Catalogue = z.object({
  countries: z.array(z.object({
    code: z.string().nullable(),
    name: z.string(),
    boxes: z.array(Box).min(1),
    polygon: z.array(Ring),
  })),
  subdivisions: z.record(
    z.string(),
    z.array(z.object({
      name: z.string(),
      /* The postal abbreviation, which the source carries for all but one
         subdivision we ship -- Gujarat, whose abbreviation is its name. */
      abbr: z.string().optional(),
      boxes: z.array(Box).min(1),
    })),
  ),
  cities: z.record(
    z.string(),
    z.array(z.object({ name: z.string(), bbox: Box })),
  ),
});

/* Parsed once at module load: the file is committed, so a mistake here is a
   build-time accident, and it should fail the first render loudly rather
   than surface as an empty picker. */
const catalogue = Catalogue.parse(data);

export type Country = (typeof catalogue.countries)[number];
export type Subdivision = {
  name: string;
  abbr?: string | undefined;
  boxes: [number, number, number, number][];
};
export type City = {
  name: string;
  bbox: [number, number, number, number];
};

/* The locale is a parameter with a default rather than only a lookup: a
   caller that memoizes on the locale has to be able to name what it
   depends on (components/PlaceSearch.tsx does), and a default keeps every
   other call site unchanged. */
export const countryName = (
  country: Country,
  locale: string = getLocale(),
): string => {
  if (country.code) {
    try {
      const display = new Intl.DisplayNames([locale], { type: "region" });
      return display.of(country.code) ?? country.name;
    } catch {
      /* An unknown code falls back to the dataset's name. */
    }
  }
  return country.name;
};

/* Sorted for the current locale on every call, because the locale can change
   under a live picker and "Germany" and "Allemagne" sort differently. */
export const countries = (): { country: Country; label: string; }[] => {
  const collator = new Intl.Collator(getLocale());
  return catalogue.countries
    .map((country) => ({ country, label: countryName(country) }))
    .sort((a, b) => collator.compare(a.label, b.label));
};

export const subdivisionsOf = (country: Country): Subdivision[] =>
  country.code ? catalogue.subdivisions[country.code] ?? [] : [];

export const citiesOf = (country: Country): City[] =>
  country.code ? catalogue.cities[country.code] ?? [] : [];

export const toRegion = (
  bbox: [number, number, number, number],
  polygon?: [number, number][][],
): Region => ({
  min_lon: bbox[0],
  min_lat: bbox[1],
  max_lon: bbox[2],
  max_lat: bbox[3],
  max_zoom: 15,
  ...(polygon && polygon.length > 0 ? { polygon } : {}),
});

/* Every region a whole-country download means: one per box, sharing the
   country's border polygon. */
export const countryRegions = (country: Country): Region[] =>
  country.boxes.map((box) => toRegion(box, country.polygon));

export const subdivisionRegions = (sub: Subdivision): Region[] =>
  sub.boxes.map((box) => toRegion(box));
