(** Interface the F*-extracted core must satisfy.

    The implementation of this module is GENERATED by [fstar.exe --codegen OCaml]
    from ../fstar/. It is a build artifact, like an object file.

    Do not hand-edit the generated .ml. Any change belongs upstream in the F*
    source or it will be silently overwritten at the next extraction. CI
    enforces this by regenerating and diffing. *)

type cell = private int
type key = string          (** 32 bytes *)

exception Out_of_range of string
exception Invalid_address of string

val total_cells : int
val address_space : int
val grid_version : string

(** {1 Grid} — all arithmetic in integer nanodegrees, never floats. *)

val point_to_cell : lat_ns:int -> lon_ns:int -> cell
val cell_to_point : cell -> int * int
val cell_bounds : cell -> int * int * int * int

(** {1 Key derivation} — PBKDF2 is deliberately slow. Call once per session
    and cache; never in the request path. *)

val derive_key : mnemonic:string -> passphrase:string -> key
val validate_mnemonic : string -> (unit, string) result

(** {1 Addresses} *)

val encode : key -> lat_ns:int -> lon_ns:int -> string
val decode : key -> string -> (int * int, string) result
