; Argon2id (the PHC winner's reference C, vendor/, pinned release 20190702,
; tarball sha256 daf972a89577f8772602bf2eb38b6a3dd3d922bf5724d45e7f9589b5e830442c,
; CC0/Apache-2.0 -- vendor/LICENSE) behind an OCaml FFI. `make sync-argon2`
; re-downloads the pinned tarball and diffs; CI runs it, so a local edit to
; vendored code fails the build rather than surviving quietly.
; A separate library, NOT part of `tessarium`: that library also compiles
; under js_of_ocaml for the browser bundle, and C stubs do not. The browser
; runs the SAME vendored C compiled to WebAssembly (wasm/argon2.wasm).
; ARGON2_NO_THREADS: p=1 is baked in the stubs, so thread.c is not vendored.
(library
 (name tessarium_argon2)
 (foreign_stubs
  (language c)
  (names argon2_stubs argon2 core encoding ref blake2b)
  (flags (:standard -std=c11 -O2 -Wall -DARGON2_NO_THREADS))
  (include_dirs vendor vendor/blake2)))

(copy_files vendor/*.c)
(copy_files vendor/blake2/*.c)
