(* Differential test of the extracted core against the committed vectors.

   These vectors are currently generated by the Python reference, which makes
   the Python the de facto source of truth. Re-anchoring them to F* is a Phase 4
   item; until then, agreement here is what says the extraction reproduces the
   validated design exactly. *)

let vectors_path = "../../vectors/vectors.json"

let failures = ref 0
let checks = ref 0

let check name ok =
  incr checks;
  if not ok then begin
    incr failures;
    Printf.printf "  FAIL  %s\n" name
  end

let check_eq name a b =
  check (Printf.sprintf "%s (got %s, want %s)" name a b) (String.equal a b)

let hex s =
  String.concat "" (List.map (fun c -> Printf.sprintf "%02x" (Char.code c))
                      (List.init (String.length s) (String.get s)))

let member k = function
  | `Assoc l -> List.assoc k l
  | _ -> failwith "expected object"

let to_int = function
  | `Int i -> i
  | `Intlit s -> int_of_string s
  | _ -> failwith "expected int"

let to_str = function `String s -> s | _ -> failwith "expected string"
let to_list = function `List l -> l | _ -> failwith "expected list"

let () =
  let json = Yojson.Safe.from_file vectors_path in

  (* constants agree with the extracted table *)
  check_eq "grid_version" Tessarium.grid_version (to_str (member "grid_version" json));
  check "total_cells"
    (Z.equal Tessarium.total_cells (Z.of_int (to_int (member "total_cells" json))));
  check "address_space"
    (Z.equal Tessarium.address_space (Z.of_int (to_int (member "address_space" json))));

  (* key derivation *)
  let keys = Hashtbl.create 8 in
  List.iter
    (fun v ->
      let name = to_str (member "name" v) in
      let mnemonic = to_str (member "mnemonic" v) in
      let passphrase =
        match member "passphrase" v with `String p -> p | _ -> ""
      in
      let key = Tessarium.derive_key ~mnemonic ~passphrase in
      Hashtbl.replace keys name key;
      check_eq (Printf.sprintf "derive_key[%s]" name) (hex key) (to_str (member "key" v)))
    (to_list (member "key_derivation" json));

  (* grid: point -> cell -> centre *)
  List.iter
    (fun v ->
      let lat_ns = to_int (member "lat_ns" v) and lon_ns = to_int (member "lon_ns" v) in
      let cell = Z.to_int (Tessarium_Grid.point_to_cell (Z.of_int lat_ns) (Z.of_int lon_ns)) in
      check
        (Printf.sprintf "point_to_cell(%d,%d) = %d want %d" lat_ns lon_ns cell
           (to_int (member "cell" v)))
        (cell = to_int (member "cell" v));
      let clat, clon = Tessarium_Grid.cell_to_point (Z.of_int cell) in
      check
        (Printf.sprintf "cell_to_point(%d) lat" cell)
        (Z.to_int clat = to_int (member "centre_lat_ns" v));
      check
        (Printf.sprintf "cell_to_point(%d) lon" cell)
        (Z.to_int clon = to_int (member "centre_lon_ns" v)))
    (to_list (member "grid_vectors" json));

  (* feistel permutation, under the fixed key the vectors were generated with
     -- not a derived one *)
  let unhex h =
    String.init (String.length h / 2) (fun i ->
        Char.chr (int_of_string ("0x" ^ String.sub h (2 * i) 2)))
  in
  let zero_key =
    unhex "00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff"
  in
  List.iter
    (fun v ->
      let x = to_int (member "x" v) and y = to_int (member "y" v) in
      let enc =
        Z.to_int
          (Tessarium_Feistel.encrypt Tessarium.round_fn zero_key Tessarium.grid_version
             (Z.of_int x))
      in
      check (Printf.sprintf "encrypt(%d) = %d want %d" x enc y) (enc = y);
      let dec =
        Z.to_int
          (Tessarium_Feistel.decrypt Tessarium.round_fn zero_key Tessarium.grid_version
             (Z.of_int y))
      in
      check (Printf.sprintf "decrypt(%d) round-trips" y) (dec = x))
    (to_list (member "feistel_vectors" json));

  (* end to end *)
  List.iter
    (fun v ->
      let key = Hashtbl.find keys (to_str (member "mnemonic" v)) in
      let lat_ns = to_int (member "lat_ns" v) and lon_ns = to_int (member "lon_ns" v) in
      let want = to_str (member "address" v) in
      let got = Tessarium.encode ~key ~lat_ns ~lon_ns in
      check_eq (Printf.sprintf "encode(%d,%d)" lat_ns lon_ns) got want;
      match Tessarium.decode ~key want with
      | Error e -> check (Printf.sprintf "decode(%s): %s" want e) false
      | Ok (dlat, dlon) ->
          let cell p q = Tessarium_Grid.point_to_cell (Z.of_int p) (Z.of_int q) in
          check
            (Printf.sprintf "decode(%s) lands in the same cell" want)
            (Z.equal (cell dlat dlon) (cell lat_ns lon_ns)))
    (to_list (member "addresses" json));

  (* The BIP-39 passphrase is case-sensitive and used verbatim. An earlier
     version folded it through the mnemonic's normaliser, so "MySecret" and
     "mysecret" produced the same map and every letter's case was thrown away.
     Nothing failed; it just quietly weakened the passphrase. *)
  let m = to_str (member "mnemonic" (List.hd (to_list (member "key_derivation" json)))) in
  let k p = hex (Tessarium.derive_key ~mnemonic:m ~passphrase:p) in
  check "passphrase case is significant" (k "MySecret" <> k "mysecret");
  check "passphrase case is significant (upper)" (k "MYSECRET" <> k "mysecret");
  check "passphrase whitespace is significant" (k " mysecret " <> k "mysecret");
  check "an empty passphrase is unaffected"
    (String.equal (k "") (hex (Tessarium.derive_key ~mnemonic:m ~passphrase:"")));
  (* And the mnemonic itself stays forgiving: its words are lowercase by
     definition, so how it was pasted must not matter. *)
  check "mnemonic case and padding do not matter"
    (String.equal
       (hex (Tessarium.derive_key ~mnemonic:("  " ^ String.uppercase_ascii m ^ "  ") ~passphrase:""))
       (k ""));

  Printf.printf "\n%d checks, %d failures\n" !checks !failures;
  if !failures > 0 then exit 1 else print_endline "all vectors reproduce"
