(* Emit an OCaml module embedding a directory of built UI assets.

   This is what makes the desktop target one file. Without it the binary serves
   from `ui/dist` at runtime, which works but means "single binary" is really
   "binary plus a directory that has to travel with it".

   Assets are stored gzipped and served with `Content-Encoding: gzip` rather
   than decompressed at startup. The js_of_ocaml core is 4.4 MB and compresses
   to about a tenth of that, and an OCaml source file containing a 4.4 MB
   string literal is slow to compile and large in the binary. Serving the
   compressed bytes straight through avoids both, and is what a browser wants
   anyway.

   If the directory is missing or empty the module is still emitted, empty, and
   the server falls back to serving from disk. A fresh clone can therefore
   `dune build` without having run the UI build first. *)

let rec walk root prefix acc =
  let entries = try Sys.readdir (Filename.concat root prefix) with _ -> [||] in
  Array.sort compare entries;
  Array.fold_left
    (fun acc name ->
      let rel = if prefix = "" then name else Filename.concat prefix name in
      let full = Filename.concat root rel in
      if Sys.is_directory full then walk root rel acc else rel :: acc)
    acc entries

let read path =
  let ic = open_in_bin path in
  let n = in_channel_length ic in
  let s = really_input_string ic n in
  close_in ic;
  s

let () =
  let root = if Array.length Sys.argv > 1 then Sys.argv.(1) else "" in
  let files =
    if root = "" || not (Sys.file_exists root) then []
    else List.rev (walk root "" [])
  in
  print_string
    "(* GENERATED by ocaml/tools/gen_assets.ml. Do not edit.\n\
    \   Each entry is (path, gzipped bytes). *)\n\n";
  print_string "let files : (string * string) list = [\n";
  List.iter
    (fun rel ->
      let body = Gzip.compress (read (Filename.concat root rel)) in
      Printf.printf "  (%S, %S);\n" rel body)
    files;
  print_string "]\n\n";
  print_string "let table : (string, string) Hashtbl.t = Hashtbl.create 64\n\n";
  print_string
    "let () = List.iter (fun (p, b) -> Hashtbl.replace table p b) files\n\n";
  print_string "let find path = Hashtbl.find_opt table path\n";
  print_string "let count = List.length files\n";
  Printf.eprintf "embedded %d assets\n" (List.length files)
