(* Emit ocaml/lib/wordlist.ml from wordlist/english.txt.

   Run by dune as part of the build, so the module cannot drift from the list
   it claims to encode. It used to be a committed file marked GENERATED with
   nothing in the tree able to generate it, which is the same as hand-written
   with a misleading comment on top. *)

let expected = 2048

let () =
  let path = Sys.argv.(1) in
  let words =
    let ic = open_in path in
    let rec go acc =
      match input_line ic with
      | line -> (
          match String.trim line with "" -> go acc | w -> go (w :: acc))
      | exception End_of_file ->
          close_in ic;
          List.rev acc
    in
    go []
  in
  let n = List.length words in
  (* BIP-39 is exactly 2048 words, and the codec's radix depends on it. A short
     list would produce a working build and wrong addresses. *)
  if n <> expected then begin
    Printf.eprintf "wordlist: expected %d words, got %d\n" expected n;
    exit 1
  end;
  print_string "(* GENERATED by ocaml/tools/gen_wordlist.ml from\n";
  print_string "   wordlist/english.txt. Do not edit. *)\n\n";
  print_string "let words = [|\n";
  List.iteri
    (fun i w ->
      if i mod 8 = 0 then print_string "  ";
      Printf.printf "%S;" w;
      if i mod 8 = 7 then print_newline () else print_char ' ')
    words;
  if n mod 8 <> 0 then print_newline ();
  print_string "|]\n\n";
  print_string "let index : (string, int) Hashtbl.t = Hashtbl.create 4096\n\n";
  print_string "let () = Array.iteri (fun i w -> Hashtbl.replace index w i) words\n"
