(* Emits fstar/check/Tessarium.Check.Expected.fst: what the EXTRACTED core
   computes, spelled as F* literals, for the checker to re-derive inside F*'s
   own evaluator.

   This is the bridge the roadmap called the largest open gap. The F* source
   is proved; the OCaml here was extracted from it by a pipeline that is
   trusted, not verified. This tool and Tessarium.Check.fst put the two on
   opposite sides of one equation: the extracted binary computes answers, and
   F*'s normalizer -- a second implementation of the language's semantics,
   sharing nothing with extraction past the parser -- recomputes them from
   the proved source. Either implementation wrong about any checked value
   fails `make check-extraction`.

   Honesty about scope: this checks extraction on the points and data below,
   not on all inputs; it is differential testing with F* itself as the
   oracle, not a verified pipeline. The round function is a concrete test
   one, spelled here with Prims' own operators -- the arithmetic layer every
   extracted expression already goes through -- and independently in the F*
   harness; the two spellings disagreeing FAILS the check, which is the
   right direction. HMAC is deliberately absent: it was never inside the
   proof (the theorems hold for any round function), and it is vector-tested
   where it lives.

   Deterministic by construction: no clock, no OS randomness. Same extracted
   core, same bytes out -- CI diffs the regenerated file against the
   committed one exactly as it does for ocaml/extracted. *)

let spf = Printf.sprintf

(* The concrete round function, over Prims arithmetic. The F* harness spells
   the same function in F* syntax; Tessarium.Check.fst names this file as
   its other half. *)
(* Prims exposes its arithmetic as infix operators; shadowing the stdlib's
   int operators with Z.t ones is confined to this one definition. *)
let rf : ('k, 't) Tessarium_Feistel.round_fn =
 fun k t i x m ->
  let open Prims in
  ((x * Z.of_int 31) + (i * Z.of_int 1000003) + (k + t)) mod m

(* Fixed key and tweak for the end-to-end points; the harness hardcodes the
   same two numerals. *)
let ck = Z.of_int 7
let ct = Z.of_int 9

(* A tiny deterministic generator (Lehmer, modulus 2^61-1) for the points
   that are not corners. Seeded by a constant: the corpus is part of the
   check's identity. *)
let lehmer = ref (Z.of_int 20260819)
let m61 = Z.sub (Z.shift_left Z.one 61) Z.one

let next bound =
  lehmer := Z.rem (Z.mul !lehmer (Z.of_string "381471956995469")) m61;
  Z.rem !lehmer bound

let z = Z.to_string

(* Negative literals need parens in F* list syntax. *)
let lit v = if Z.sign v < 0 then spf "(%s)" (z v) else z v

let int_list name values =
  spf "[@@\"opaque_to_smt\"]\nlet %s : list int = [\n  %s\n]\n" name
    (String.concat ";\n  " (List.map lit values))

let () =
  let out = Sys.argv.(1) in
  let b = Buffer.create (1 lsl 20) in
  let addf fmt = Printf.ksprintf (Buffer.add_string b) fmt in

  addf "module Tessarium.Check.Expected\n\n";
  addf "/// GENERATED by ocaml/tools/gen_check.ml from the EXTRACTED core.\n";
  addf "/// DO NOT EDIT. These are the extracted binary's answers;\n";
  addf "/// Tessarium.Check.fst makes F* recompute every one of them.\n\n";

  (* ----------------------------------------------------------- constants *)
  let open Tessarium_Table in
  addf "let rows : int = %s\n" (z rows);
  addf "let bands : int = %s\n" (z bands);
  addf "let rows_per_band : int = %s\n" (z rows_per_band);
  addf "let total_cells : int = %s\n" (z total_cells);
  addf "let max_col_count : int = %s\n" (z max_col_count);
  addf "let grid_version : string = \"%s\"\n\n" grid_version;

  (* ----------------------------------------------------------- the table *)
  (* The whole cumulative table, not a sample: it is two thirds of every
     extracted line, and one list equality checks all 4097 entries at once. *)
  Buffer.add_string b
    (int_list "cumcols" Tessarium_Table_Data.cumcols_list);
  addf "\n";

  (* ------------------------------------------------------------- feistel *)
  let fe_a = Tessarium_Spec.fe_a and fe_b = Tessarium_Spec.fe_b in
  let addr_space = Tessarium_Spec.addr_space in
  let fe_xs =
    [ Z.zero; Z.one; Z.pred fe_a; fe_a; Z.pred fe_b; fe_b;
      Z.pred addr_space ]
    @ List.init 9 (fun _ -> next addr_space)
  in
  let fe_ks = List.mapi (fun i _ -> Z.of_int (i * 13)) fe_xs in
  let fe_ts = List.mapi (fun i _ -> Z.of_int (i * 5 + 2)) fe_xs in
  let fe_ys =
    List.map2
      (fun (k, t) x -> Tessarium_Feistel.encrypt rf k t x)
      (List.combine fe_ks fe_ts) fe_xs
  in
  Buffer.add_string b (int_list "fe_k" fe_ks);
  Buffer.add_string b (int_list "fe_t" fe_ts);
  Buffer.add_string b (int_list "fe_x" fe_xs);
  Buffer.add_string b (int_list "fe_y" fe_ys);
  addf "\n";

  (* --------------------------------------------------------------- codec *)
  let num_max = Tessarium_Spec.num_max and words = Tessarium_Spec.words in
  let ix =
    [ Z.zero; Z.pred addr_space; Z.pred num_max; num_max;
      Z.mul words num_max ]
    @ List.init 5 (fun _ -> next addr_space)
  in
  let addr_row i =
    let w1, w2, w3, n = Tessarium_Codec.to_address i in
    spf "(%s, %s, %s, %s, %s)" (lit i) (lit w1) (lit w2) (lit w3) (lit n)
  in
  addf "[@@\"opaque_to_smt\"]\nlet codec : list (int & int & int & int & int) = [\n  %s\n]\n\n"
    (String.concat ";\n  " (List.map addr_row ix));

  (* ---------------------------------------------------------- end to end *)
  (* Six points, each a full encode plus the decode of its own answer: two
     straddling a band seam (the seam latitude comes from the extracted
     Spec.edge, the same discipline the differential corpus uses -- this
     file must not independently reproduce a bug in it), the north pole,
     the antimeridian on the equator, the origin, and one generated point. *)
  let lat_min = Z.of_string "-90000000000" in
  let lat_span = Z.of_string "180000000000" in
  let lon_min = Z.of_string "-180000000000" in
  let lon_span = Z.of_string "360000000000" in
  (* Band 1337, not 2048: the middle band's seam is the equator, which the
     origin point below already stands on. *)
  let seam =
    Tessarium_Spec.edge
      (Z.mul (Z.of_int 1337) rows_per_band)
      lat_min lat_span rows
  in
  let pts =
    [ (seam, Z.of_int 5_000_000);
      (Z.pred seam, Z.of_int 5_000_000);
      (Z.add lat_min lat_span, Z.zero);
      (* The exact bottom of the domain: band 0's first row, band_search's
         lower extreme, the cell-0 region of cell_to_point. *)
      (lat_min, Z.of_int 7_000_000);
      (Z.zero, lon_min);
      (Z.zero, Z.zero);
      ( Z.add lat_min (next lat_span),
        Z.add lon_min (next lon_span) ) ]
  in
  let e2e_row (la, lo) =
    let w1, w2, w3, n = Tessarium_Api.encode rf ck ct la lo in
    match Tessarium_Api.decode rf ck ct (w1, w2, w3, n) with
    | FStar_Pervasives_Native.Some (cla, clo) ->
        spf "(%s, %s, %s, %s, %s, %s, %s, %s)" (lit la) (lit lo) (lit w1)
          (lit w2) (lit w3) (lit n) (lit cla) (lit clo)
    | FStar_Pervasives_Native.None ->
        failwith "an encoded address decoded to None: extraction is broken"
  in
  addf
    "[@@\"opaque_to_smt\"]\nlet e2e : list (int & int & int & int & int & int & int & int) = [\n  %s\n]\n\n"
    (String.concat ";\n  " (List.map e2e_row pts));

  (* ------------------------------------------------- the rejection path *)
  (* Two addresses that decode to nothing, found by scanning: about 35%% of
     the address space permutes past total_cells, and the None arm is a
     branch extraction could lose. *)
  let rec find_none acc want =
    if want = 0 then List.rev acc
    else
      let a = Tessarium_Codec.to_address (next addr_space) in
      match Tessarium_Api.decode rf ck ct a with
      | FStar_Pervasives_Native.None -> find_none (a :: acc) (want - 1)
      | FStar_Pervasives_Native.Some _ -> find_none acc want
  in
  let nones = find_none [] 2 in
  addf "[@@\"opaque_to_smt\"]\nlet nones : list (int & int & int & int) = [\n  %s\n]\n\n"
    (String.concat ";\n  "
       (List.map
          (fun (w1, w2, w3, n) ->
            spf "(%s, %s, %s, %s)" (lit w1) (lit w2) (lit w3) (lit n))
          nones));

  (* ------------------------------------------------------------- bounds *)
  let bla, blo = (Z.of_string "48853492000", Z.of_string "2348392000") in
  let s, w, n_, e = Tessarium_Api.bounds_of_point bla blo in
  addf "let bounds_in : int & int = (%s, %s)\n" (lit bla) (lit blo);
  addf "let bounds_out : int & int & int & int = (%s, %s, %s, %s)\n"
    (lit s) (lit w) (lit n_) (lit e);

  (* "-" skips the Expected.fst write: test-lowstar needs only the C
     header and must not side-effect a committed file it does not check
     (nor race test-extraction's readers of it under make -j). *)
  if out <> "-" then begin
    let oc = open_out out in
    output_string oc (Buffer.contents b);
    close_out oc;
    Printf.printf "expected values written to %s\n" out
  end;

  (* ------------------------------------------------- the C core's copy *)
  (* The same Feistel vectors as C initializers, when a second path is
     given: fstar/low/check_main.c replays them against the KaRaMeL-emitted
     core, the third implementation to answer for these numbers. Committed
     and CI-diffed exactly like this file's F* half. *)
  if Array.length Sys.argv > 2 then begin
    let hb = Buffer.create 4096 in
    let addh fmt = Printf.ksprintf (Buffer.add_string hb) fmt in
    addh "/* GENERATED by ocaml/tools/gen_check.ml from the EXTRACTED core.\n";
    addh "   DO NOT EDIT. The Feistel vectors of Tessarium.Check.Expected.fst\n";
    addh "   as C initializers, replayed by check_main.c against the\n";
    addh "   KaRaMeL-emitted core. */\n";
    addh "#include <stdint.h>\n\n";
    addh "#define FE_COUNT %d\n\n" (List.length fe_xs);
    let arr name vs =
      addh "static const uint64_t %s[FE_COUNT] = {\n  %s\n};\n\n" name
        (String.concat ",\n  " (List.map (fun v -> Z.to_string v ^ "ULL") vs))
    in
    arr "vec_k" fe_ks;
    arr "vec_t" fe_ts;
    arr "vec_x" fe_xs;
    arr "vec_y" fe_ys;

    (* The cumulative table as a C array. The C grid's lookup answers from
       this; Check.Table cross-examines the same 4097 entries against the
       proved source, and the harness pins the count. *)
    let cum = Tessarium_Table_Data.cumcols_list in
    addh "#define CUM_COUNT %d\n\n" (List.length cum);
    addh "static const uint64_t cum_table[CUM_COUNT] = {\n  %s\n};\n\n"
      (String.concat ",\n  " (List.map (fun v -> Z.to_string v ^ "ULL") cum));

    (* Grid vectors: the e2e points plus five generated, all THREE grid
       maps per point (cell, centre, bounds), as offsets from the domain
       corner -- the representation the C boundary speaks. *)
    let gpts =
      pts
      @ List.init 5 (fun _ ->
            ( Z.add lat_min (next (Z.succ lat_span)),
              Z.add lon_min (next (Z.succ lon_span)) ))
    in
    let grows =
      List.map
        (fun (la, lo) ->
          let cell = Tessarium_Grid.point_to_cell la lo in
          let cla, clo = Tessarium_Grid.cell_to_point cell in
          if Tessarium_Grid.point_to_cell cla clo <> cell then
            failwith "a cell centre did not round-trip: extraction is broken";
          let blat_lo, blat_hi, blon_lo, blon_hi =
            Tessarium_Grid.cell_bounds cell
          in
          [ Z.sub la lat_min; Z.sub lo lon_min; cell;
            Z.sub cla lat_min; Z.sub clo lon_min;
            Z.sub blat_lo lat_min; Z.sub blat_hi lat_min;
            Z.sub blon_lo lon_min; Z.sub blon_hi lon_min ])
        gpts
    in
    addh "#define GRID_COUNT %d\n\n" (List.length grows);
    List.iteri
      (fun fi name ->
        addh "static const uint64_t %s[GRID_COUNT] = {\n  %s\n};\n\n" name
          (String.concat ",\n  "
             (List.map (fun row -> Z.to_string (List.nth row fi) ^ "ULL") grows)))
      [ "gvec_dlat"; "gvec_dlon"; "gvec_cell"; "gvec_cdlat"; "gvec_cdlon";
        "gvec_blatlo"; "gvec_blathi"; "gvec_blonlo"; "gvec_blonhi" ];
    let oc = open_out Sys.argv.(2) in
    output_string oc (Buffer.contents hb);
    close_out oc;
    Printf.printf "feistel vectors written to %s\n" Sys.argv.(2)
  end
