(* Emits fstar/check/Tessarium.Check.Expected.fst: what the EXTRACTED core
   computes, spelled as F* literals, for the checker to re-derive inside F*'s
   own evaluator.

   This is the bridge the roadmap called the largest open gap. The F* source
   is proved; the OCaml here was extracted from it by a pipeline that is
   trusted, not verified. This tool and Tessarium.Check.fst put the two on
   opposite sides of one equation: the extracted binary computes answers, and
   F*'s normalizer -- a second implementation of the language's semantics,
   sharing nothing with extraction past the parser -- recomputes them from
   the proved source. Either implementation wrong about any checked value
   fails `make check-extraction`.

   Honesty about scope: this checks extraction on the points and data below,
   not on all inputs; it is differential testing with F* itself as the
   oracle, not a verified pipeline. The round function is a concrete test
   one, spelled here with Prims' own operators -- the arithmetic layer every
   extracted expression already goes through -- and independently in the F*
   harness; the two spellings disagreeing FAILS the check, which is the
   right direction. HMAC is deliberately absent: it was never inside the
   proof (the theorems hold for any round function), and it is vector-tested
   where it lives.

   Deterministic by construction: no clock, no OS randomness. Same extracted
   core, same bytes out -- CI diffs the regenerated file against the
   committed one exactly as it does for ocaml/extracted. *)

let spf = Printf.sprintf

(* The concrete round function, over Prims arithmetic. The F* harness spells
   the same function in F* syntax; Tessarium.Check.fst names this file as
   its other half. *)
(* Prims exposes its arithmetic as infix operators; shadowing the stdlib's
   int operators with Z.t ones is confined to this one definition. *)
let rf : ('k, 't) Tessarium_Feistel.round_fn =
 fun k t i x m ->
  let open Prims in
  ((x * Z.of_int 31) + (i * Z.of_int 1000003) + (k + t)) mod m

(* Fixed key and tweak for the end-to-end points; the harness hardcodes the
   same two numerals. *)
let ck = Z.of_int 7
let ct = Z.of_int 9

(* A tiny deterministic generator (Lehmer, modulus 2^61-1) for the points
   that are not corners. Seeded by a constant: the corpus is part of the
   check's identity. *)
let lehmer = ref (Z.of_int 20260819)
let m61 = Z.sub (Z.shift_left Z.one 61) Z.one

let next bound =
  lehmer := Z.rem (Z.mul !lehmer (Z.of_string "381471956995469")) m61;
  Z.rem !lehmer bound

let z = Z.to_string

(* Negative literals need parens in F* list syntax. *)
let lit v = if Z.sign v < 0 then spf "(%s)" (z v) else z v

let int_list name values =
  spf "[@@\"opaque_to_smt\"]\nlet %s : list int = [\n  %s\n]\n" name
    (String.concat ";\n  " (List.map lit values))

let () =
  let out = Sys.argv.(1) in
  let b = Buffer.create (1 lsl 20) in
  let addf fmt = Printf.ksprintf (Buffer.add_string b) fmt in

  addf "module Tessarium.Check.Expected\n\n";
  addf "/// GENERATED by ocaml/tools/gen_check.ml from the EXTRACTED core.\n";
  addf "/// DO NOT EDIT. These are the extracted binary's answers;\n";
  addf "/// Tessarium.Check.fst makes F* recompute every one of them.\n\n";

  (* ----------------------------------------------------------- constants *)
  let open Tessarium_Table in
  addf "let rows : int = %s\n" (z rows);
  addf "let bands : int = %s\n" (z bands);
  addf "let rows_per_band : int = %s\n" (z rows_per_band);
  addf "let total_cells : int = %s\n" (z total_cells);
  addf "let max_col_count : int = %s\n" (z max_col_count);
  addf "let grid_version : string = \"%s\"\n\n" grid_version;

  (* ----------------------------------------------------------- the table *)
  (* The whole cumulative table, not a sample: it is two thirds of every
     extracted line, and one list equality checks all 4097 entries at once. *)
  Buffer.add_string b
    (int_list "cumcols" Tessarium_Table_Data.cumcols_list);
  addf "\n";

  (* ------------------------------------------------------------- feistel *)
  let fe_a = Tessarium_Spec.fe_a and fe_b = Tessarium_Spec.fe_b in
  let addr_space = Tessarium_Spec.addr_space in
  let fe_xs =
    [ Z.zero; Z.one; Z.pred fe_a; fe_a; Z.pred fe_b; fe_b;
      Z.pred addr_space ]
    @ List.init 9 (fun _ -> next addr_space)
  in
  let fe_ks = List.mapi (fun i _ -> Z.of_int (i * 13)) fe_xs in
  let fe_ts = List.mapi (fun i _ -> Z.of_int (i * 5 + 2)) fe_xs in
  let fe_ys =
    List.map2
      (fun (k, t) x -> Tessarium_Feistel.encrypt rf k t x)
      (List.combine fe_ks fe_ts) fe_xs
  in
  Buffer.add_string b (int_list "fe_k" fe_ks);
  Buffer.add_string b (int_list "fe_t" fe_ts);
  Buffer.add_string b (int_list "fe_x" fe_xs);
  Buffer.add_string b (int_list "fe_y" fe_ys);
  addf "\n";

  (* --------------------------------------------------------------- codec *)
  let num_max = Tessarium_Spec.num_max and words = Tessarium_Spec.words in
  let ix =
    [ Z.zero; Z.pred addr_space; Z.pred num_max; num_max;
      Z.mul words num_max ]
    @ List.init 5 (fun _ -> next addr_space)
  in
  let crows =
    List.map (fun i ->
        let w1, w2, w3, n = Tessarium_Codec.to_address i in
        (i, w1, w2, w3, n)) ix
  in
  let addr_row (i, w1, w2, w3, n) =
    spf "(%s, %s, %s, %s, %s)" (lit i) (lit w1) (lit w2) (lit w3) (lit n)
  in
  addf "[@@\"opaque_to_smt\"]\nlet codec : list (int & int & int & int & int) = [\n  %s\n]\n\n"
    (String.concat ";\n  " (List.map addr_row crows));

  (* ---------------------------------------------------------- end to end *)
  (* Seven points, each a full encode plus the decode of its own answer: two
     straddling a band seam (the seam latitude comes from the extracted
     Spec.edge, the same discipline the differential corpus uses -- this
     file must not independently reproduce a bug in it), the north pole,
     the antimeridian on the equator, the origin, and one generated point. *)
  let lat_min = Z.of_string "-90000000000" in
  let lat_span = Z.of_string "180000000000" in
  let lon_min = Z.of_string "-180000000000" in
  let lon_span = Z.of_string "360000000000" in
  (* Band 1337, not 2048: the middle band's seam is the equator, which the
     origin point below already stands on. *)
  let seam =
    Tessarium_Spec.edge
      (Z.mul (Z.of_int 1337) rows_per_band)
      lat_min lat_span rows
  in
  let pts =
    [ (seam, Z.of_int 5_000_000);
      (Z.pred seam, Z.of_int 5_000_000);
      (Z.add lat_min lat_span, Z.zero);
      (* The exact bottom of the domain: band 0's first row, band_search's
         lower extreme, the cell-0 region of cell_to_point. *)
      (lat_min, Z.of_int 7_000_000);
      (Z.zero, lon_min);
      (Z.zero, Z.zero);
      ( Z.add lat_min (next lat_span),
        Z.add lon_min (next lon_span) ) ]
  in
  let erows =
    List.map
      (fun (la, lo) ->
        let w1, w2, w3, n = Tessarium_Api.encode rf ck ct la lo in
        match Tessarium_Api.decode rf ck ct (w1, w2, w3, n) with
        | FStar_Pervasives_Native.Some (cla, clo) ->
            (la, lo, w1, w2, w3, n, cla, clo)
        | FStar_Pervasives_Native.None ->
            failwith "an encoded address decoded to None: extraction is broken")
      pts
  in
  let e2e_row (la, lo, w1, w2, w3, n, cla, clo) =
    spf "(%s, %s, %s, %s, %s, %s, %s, %s)" (lit la) (lit lo) (lit w1)
      (lit w2) (lit w3) (lit n) (lit cla) (lit clo)
  in
  addf
    "[@@\"opaque_to_smt\"]\nlet e2e : list (int & int & int & int & int & int & int & int) = [\n  %s\n]\n\n"
    (String.concat ";\n  " (List.map e2e_row erows));

  (* ------------------------------------------------- the rejection path *)
  (* Two addresses that decode to nothing, found by scanning: about 35%% of
     the address space permutes past total_cells, and the None arm is a
     branch extraction could lose. *)
  let rec find_none acc want =
    if want = 0 then List.rev acc
    else
      let a = Tessarium_Codec.to_address (next addr_space) in
      match Tessarium_Api.decode rf ck ct a with
      | FStar_Pervasives_Native.None -> find_none (a :: acc) (want - 1)
      | FStar_Pervasives_Native.Some _ -> find_none acc want
  in
  let nones = find_none [] 2 in
  addf "[@@\"opaque_to_smt\"]\nlet nones : list (int & int & int & int) = [\n  %s\n]\n\n"
    (String.concat ";\n  "
       (List.map
          (fun (w1, w2, w3, n) ->
            spf "(%s, %s, %s, %s)" (lit w1) (lit w2) (lit w3) (lit n))
          nones));

  (* ------------------------------------------------------------- bounds *)
  let bla, blo = (Z.of_string "48853492000", Z.of_string "2348392000") in
  let s, w, n_, e = Tessarium_Api.bounds_of_point bla blo in
  addf "let bounds_in : int & int = (%s, %s)\n" (lit bla) (lit blo);
  addf "let bounds_out : int & int & int & int = (%s, %s, %s, %s)\n"
    (lit s) (lit w) (lit n_) (lit e);


  (* ---------------------------------------------- the REAL round function *)
  (* Everything above drives the harness round function; these rows drive
     the PRODUCTION one -- digestif's HMAC-SHA256 through Crypto.round_fn,
     the exact bytes the server signs with. Now that the round function
     lives inside the proof (Tessarium.Low.Hmac), the evaluator and the
     C harness both re-derive digestif's answers from the proved source;
     these are the vectors they replay. Keys are deterministic 32-byte
     patterns: production keys are PBKDF2 output, but any 32 bytes walk
     the same code path. *)
  (* A dedicated generator state: the legacy stream's consumers (the five
     generated grid points among them) draw AFTER this code runs, and
     sharing the stream would silently reshuffle their corpus. *)
  let lehmer_real = ref (Z.of_int 20260820) in
  let next_real bound =
    lehmer_real := Z.rem (Z.mul !lehmer_real (Z.of_string "381471956995469")) m61;
    Z.rem !lehmer_real bound
  in
  let real_key v =
    String.init 32 (fun j -> Char.chr (((v * 37) + (j * 11) + 5) land 0xff))
  in
  let kw key =
    List.init 8 (fun j ->
        let byte p = Z.of_int (Char.code key.[(4 * j) + p]) in
        Z.add
          (Z.add (Z.shift_left (byte 0) 24) (Z.shift_left (byte 1) 16))
          (Z.add (Z.shift_left (byte 2) 8) (byte 3)))
  in
  let rf_rows =
    List.init 16 (fun v ->
        let key = real_key (v / 4) in
        let i = ((v * 3) mod 16) + 1 in
        let x = next_real fe_b in
        let m = if i land 1 = 1 then fe_a else fe_b in
        let r = Tessarium.round_fn key Tessarium.tweak (Z.of_int i) x m in
        (kw key, Z.of_int i, x, m, r))
  in
  let tup8 l = spf "(%s)" (String.concat ", " (List.map lit l)) in
  addf
    "[@@\"opaque_to_smt\"]\nlet real_rf_keys : list (int & int & int & int & int & int & int & int) = [\n  %s\n]\n"
    (String.concat ";\n  " (List.map (fun (k, _, _, _, _) -> tup8 k) rf_rows));
  addf
    "[@@\"opaque_to_smt\"]\nlet real_rf : list (int & int & int & int) = [\n  %s\n]\n\n"
    (String.concat ";\n  "
       (List.map
          (fun (_, i, x, m, r) ->
            spf "(%s, %s, %s, %s)" (lit i) (lit x) (lit m) (lit r))
          rf_rows));

  (* Real-key end-to-end compositions and rejections, C-harness only: the
     evaluator walks the round function above, and a full 16-round encode
     through the normalizer costs what 16 walks cost -- the C leg replays
     these against the same production answers instead. *)
  let real_e2e =
    List.concat_map
      (fun kv ->
        let key = real_key kv in
        List.map
          (fun (la, lo) ->
            let w1, w2, w3, n =
              Tessarium_Api.encode Tessarium.round_fn key
                Tessarium.tweak la lo
            in
            match
              Tessarium_Api.decode Tessarium.round_fn key
                Tessarium.tweak (w1, w2, w3, n)
            with
            | FStar_Pervasives_Native.Some (cla, clo) ->
                kw key
                @ [ Z.sub la lat_min; Z.sub lo lon_min; w1; w2; w3; n;
                    Z.sub cla lat_min; Z.sub clo lon_min ]
            | FStar_Pervasives_Native.None ->
                failwith
                  "a real-key encode decoded to None: extraction is broken")
          pts)
      [ 0; 1 ]
  in
  let real_nones =
    List.map
      (fun kv ->
        let key = real_key kv in
        let rec go () =
          let w1, w2, w3, n =
            Tessarium_Codec.to_address (next_real addr_space)
          in
          match
            Tessarium_Api.decode Tessarium.round_fn key Tessarium.tweak
              (w1, w2, w3, n)
          with
          | FStar_Pervasives_Native.None -> kw key @ [ w1; w2; w3; n ]
          | FStar_Pervasives_Native.Some _ -> go ()
        in
        go ())
      [ 0; 1 ]
  in

  (* "-" skips the Expected.fst write: test-lowstar needs only the C
     header and must not side-effect a committed file it does not check
     (nor race test-extraction's readers of it under make -j). *)
  if out <> "-" then begin
    let oc = open_out out in
    output_string oc (Buffer.contents b);
    close_out oc;
    Printf.printf "expected values written to %s\n" out
  end;

  (* ------------------------------------------------- the C core's copy *)
  (* The same Feistel vectors as C initializers, when a second path is
     given: fstar/low/check_main.c replays them against the KaRaMeL-emitted
     core, the third implementation to answer for these numbers. Committed
     and CI-diffed exactly like this file's F* half. *)
  if Array.length Sys.argv > 2 then begin
    let hb = Buffer.create 4096 in
    let addh fmt = Printf.ksprintf (Buffer.add_string hb) fmt in
    addh "/* GENERATED by ocaml/tools/gen_check.ml from the EXTRACTED core.\n";
    addh "   DO NOT EDIT. Feistel, grid, codec, end-to-end and REAL round\n";
    addh "   function vectors plus the cumulative band table, replayed by\n";
    addh "   check_main.c\n";
    addh "   against the KaRaMeL-emitted core. Every ULL literal below is\n";
    addh "   re-parsed and compared against the in-memory values right\n";
    addh "   after this file is written. */\n";
    addh "#include <stdint.h>\n\n";
    addh "#define FE_COUNT %d\n\n" (List.length fe_xs);
    (* Every value printed into the header, in file order. The emission
       path is unproved OCaml; re-reading the written bytes and comparing
       them against this list is what pins the header's CONTENT, where
       CI's byte-diff only pins its stability. *)
    let toks : Z.t list ref = ref [] in
    let arr name vs =
      toks := !toks @ vs;
      addh "static const uint64_t %s[FE_COUNT] = {\n  %s\n};\n\n" name
        (String.concat ",\n  " (List.map (fun v -> Z.to_string v ^ "ULL") vs))
    in
    arr "vec_k" fe_ks;
    arr "vec_t" fe_ts;
    arr "vec_x" fe_xs;
    arr "vec_y" fe_ys;

    (* The cumulative table as a C array. The C grid's lookup answers from
       this; Check.Table cross-examines the same 4097 entries against the
       proved source, and the harness pins the count. *)
    let cum = Tessarium_Table_Data.cumcols_list in
    toks := !toks @ cum;
    addh "#define CUM_COUNT %d\n\n" (List.length cum);
    addh "static const uint64_t cum_table[CUM_COUNT] = {\n  %s\n};\n\n"
      (String.concat ",\n  " (List.map (fun v -> Z.to_string v ^ "ULL") cum));

    (* Grid vectors: the e2e points plus five generated, all THREE grid
       maps per point (cell, centre, bounds), as offsets from the domain
       corner -- the representation the C boundary speaks. *)
    (* pts, plus the +180 meridian on the equator -- the one input that
       takes the longitude FOLD branch, which no e2e point reaches (the
       antimeridian e2e point is -180, already folded) -- plus five
       generated. Fixed points come before the draws, so the draws land on
       the same Lehmer states as before. *)
    let gpts =
      pts
      @ [ (Z.zero, Z.add lon_min lon_span) ]
      @ List.init 5 (fun _ ->
            ( Z.add lat_min (next (Z.succ lat_span)),
              Z.add lon_min (next (Z.succ lon_span)) ))
    in
    let grows =
      List.map
        (fun (la, lo) ->
          let cell = Tessarium_Grid.point_to_cell la lo in
          let cla, clo = Tessarium_Grid.cell_to_point cell in
          if Tessarium_Grid.point_to_cell cla clo <> cell then
            failwith "a cell centre did not round-trip: extraction is broken";
          let blat_lo, blat_hi, blon_lo, blon_hi =
            Tessarium_Grid.cell_bounds cell
          in
          [ Z.sub la lat_min; Z.sub lo lon_min; cell;
            Z.sub cla lat_min; Z.sub clo lon_min;
            Z.sub blat_lo lat_min; Z.sub blat_hi lat_min;
            Z.sub blon_lo lon_min; Z.sub blon_hi lon_min ])
        gpts
    in
    addh "#define GRID_COUNT %d\n\n" (List.length grows);
    List.iteri
      (fun fi name ->
        let col = List.map (fun row -> List.nth row fi) grows in
        toks := !toks @ col;
        addh "static const uint64_t %s[GRID_COUNT] = {\n  %s\n};\n\n" name
          (String.concat ",\n  "
             (List.map (fun v -> Z.to_string v ^ "ULL") col)))
      [ "gvec_dlat"; "gvec_dlon"; "gvec_cell"; "gvec_cdlat"; "gvec_cdlon";
        "gvec_blatlo"; "gvec_blathi"; "gvec_blonlo"; "gvec_blonhi" ];
    (* Codec vectors, the e2e compositions (key 7, tweak 9 -- the harness
       hardcodes both, pinning the keys by hand), and the two rejected
       addresses. All reuse the rows Expected.fst was written from. *)
    let zcols name cols rows count_name =
      List.iteri
        (fun fi field ->
          let col = List.map (fun row -> List.nth row fi) rows in
          toks := !toks @ col;
          addh "static const uint64_t %s_%s[%s] = {\n  %s\n};\n\n" name field
            count_name
            (String.concat ",\n  "
               (List.map (fun v -> Z.to_string v ^ "ULL") col)))
        cols
    in
    addh "#define CODEC_COUNT %d\n\n" (List.length crows);
    zcols "cvec" [ "i"; "w1"; "w2"; "w3"; "n" ]
      (List.map (fun (i, w1, w2, w3, n) -> [ i; w1; w2; w3; n ]) crows)
      "CODEC_COUNT";
    addh "#define E2E_COUNT %d\n\n" (List.length erows);
    zcols "evec" [ "dlat"; "dlon"; "w1"; "w2"; "w3"; "n"; "cdlat"; "cdlon" ]
      (List.map
         (fun (la, lo, w1, w2, w3, n, cla, clo) ->
           [ Z.sub la lat_min; Z.sub lo lon_min; w1; w2; w3; n;
             Z.sub cla lat_min; Z.sub clo lon_min ])
         erows)
      "E2E_COUNT";
    addh "#define NONE_COUNT %d\n\n" (List.length nones);
    zcols "nvec" [ "w1"; "w2"; "w3"; "n" ]
      (List.map (fun (w1, w2, w3, n) -> [ w1; w2; w3; n ]) nones)
      "NONE_COUNT";
    addh "#define REAL_RF_COUNT %d\n\n" (List.length rf_rows);
    zcols "rvec"
      [ "k0"; "k1"; "k2"; "k3"; "k4"; "k5"; "k6"; "k7"; "i"; "x"; "m"; "r" ]
      (List.map (fun (k, i, x, m, r) -> k @ [ i; x; m; r ]) rf_rows)
      "REAL_RF_COUNT";
    addh "#define REAL_E2E_COUNT %d\n\n" (List.length real_e2e);
    zcols "revec"
      [ "k0"; "k1"; "k2"; "k3"; "k4"; "k5"; "k6"; "k7";
        "dlat"; "dlon"; "w1"; "w2"; "w3"; "n"; "cdlat"; "cdlon" ]
      real_e2e "REAL_E2E_COUNT";
    addh "#define REAL_NONE_COUNT %d\n\n" (List.length real_nones);
    zcols "rnvec"
      [ "k0"; "k1"; "k2"; "k3"; "k4"; "k5"; "k6"; "k7"; "w1"; "w2"; "w3"; "n" ]
      real_nones "REAL_NONE_COUNT";
    let oc = open_out Sys.argv.(2) in
    output_string oc (Buffer.contents hb);
    close_out oc;
    (* Read the written file back and compare every ULL literal, in order,
       against the values in memory. Catches emission bugs (a misprinted
       digit, a dropped or duplicated entry) that CI's regenerate-and-diff
       cannot: a deterministic misprint diffs clean. *)
    let ic = open_in Sys.argv.(2) in
    let n = in_channel_length ic in
    let written = really_input_string ic n in
    close_in ic;
    let re = Str.regexp "\\([0-9]+\\)ULL" in
    let rec scan pos acc =
      match Str.search_forward re written pos with
      | p -> scan (p + String.length (Str.matched_string written))
               (Z.of_string (Str.matched_group 1 written) :: acc)
      | exception Not_found -> List.rev acc
    in
    let found = scan 0 [] in
    if List.length found <> List.length !toks then
      failwith
        (spf "header self-check: %d literals written, %d expected"
           (List.length found) (List.length !toks));
    List.iteri
      (fun i (a, b) ->
        if Z.compare a b <> 0 then
          failwith (spf "header self-check: literal %d is %s, expected %s"
                      i (Z.to_string a) (Z.to_string b)))
      (List.combine found !toks);
    Printf.printf "vectors written to %s (%d literals verified back)\n"
      Sys.argv.(2) (List.length found)
  end
